# Arithmatics

In [2]:
import numpy as np


In [3]:
var=np.array([1,2,3,4])
new_1=var + 3
print(new_1)

[4 5 6 7]


In [4]:
var1=np.array([1,2,3,4,5])
var2=np.array([3,6,3,2,5])
new_2= var1+ var2
print(new_2)

[ 4  8  6  6 10]


In [6]:
var3=np.array([[1,2,3,4],[5,6,7,4]])
new_3=var3 + 3
print(new_3)

[[ 4  5  6  7]
 [ 8  9 10  7]]


In [7]:
var4=np.array([[1,2,3,4],[5,6,7,4]])
var5=np.array([[3,6,3,5],[9,4,3,6]])
new_4=var4 + var5
print(new_4)

[[ 4  8  6  9]
 [14 10 10 10]]


In [8]:
new_add1=np.add(var4,var5)
print(new_add1)

[[ 4  8  6  9]
 [14 10 10 10]]


# Multiply

In [13]:
new_m1=np.multiply(var4,var5)
print(new_m1)

[[ 3 12  9 20]
 [45 24 21 24]]


# Subtract

In [12]:
new_sub=np.subtract(var4,var5)
print(new_sub)

[[-2 -4  0 -1]
 [-4  2  4 -2]]


# Power

In [14]:
new_pow= np.power(var4,3)
print(new_pow)

[[  1   8  27  64]
 [125 216 343  64]]
