In [2]:
import numpy as np

In [17]:
%timeit np.arange(1,100)**4

4.25 μs ± 237 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [18]:
%timeit [j**4 for j in range(1,100)]

14.5 μs ± 585 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [22]:
x=np.array([1,2,3,4,5])
print(x)

print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [23]:
l=[]
for i in range(1,4):
    int_1=input("Enter : ")
    l.append(int_1)

print(l)
    


Enter :  12
Enter :  13
Enter :  14


['12', '13', '14']


In [26]:
list=[]
while True:
    int_1=input("Enter : ")
    if int_1.lower() =="exit":
        break
    else:
        list.append(int_1)

print(list)
    

Enter :  hwll
Enter :  jbf
Enter :  sdf
Enter :  sf
Enter :  EXIt


['hwll', 'jbf', 'sdf', 'sf']


In [4]:
ar1=np.array([1,24,4,56,3])
print(ar1.ndim)
print(ar1)


1
[ 1 24  4 56  3]


In [5]:
ar2=np.array([[1,2,4,56]])
print(ar2)
print(ar2.ndim)


[[ 1  2  4 56]]
2


In [6]:
ar3=np.array([[[2,3,5,6,3]]])
print(ar3.ndim)
print(ar3)

3
[[[2 3 5 6 3]]]


In [9]:
arn=np.array([1,2,3,4,5],ndmin=10)
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3 4 5]]]]]]]]]]
10
