Zeros

In [2]:
import numpy as np

In [5]:
zero=np.zeros(4)
zero1=np.zeros((3,4))
print(zero)
print("--------------")
print(zero1)


[0. 0. 0. 0.]
--------------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Ones

In [7]:
ar_one=np.ones(3)
print(ar_one)

[1. 1. 1.]


Empty

In [8]:
ar_emp=np.empty(4)
print(ar_emp)

[0. 0. 0. 0.]


Range

In [10]:
ar_ran=np.arange(1,10)
print(ar_ran)

[1 2 3 4 5 6 7 8 9]


Diagonal

In [12]:
ar_dia=np.eye(4)
print(ar_dia)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Linspace

In [19]:
ar_linspace=np.linspace(0,20,num=5)
print(ar_linspace)

[ 0.  5. 10. 15. 20.]
