Data Type

In [1]:
import numpy as np


In [3]:
x= np.array([1,2,4,53])
print("Data Type : ",x.dtype)

Data Type :  int32


In [6]:
x1= np.array([1,2,4,53],dtype=np.float32)
print("Data Type : ",x1.dtype)
print(x1)

Data Type :  float32
[ 1.  2.  4. 53.]


In [9]:
x2= np.array([1,2,4,53],dtype="S")
print("Data Type : ",x2.dtype)
print(x2)

Data Type :  |S2
[b'1' b'2' b'4' b'53']


In [18]:
x3= np.array([1,2,4,53])
new = np.float32(x3)
print("Data Type : ",new.dtype)
print(new)

Data Type :  float32
[ 1.  2.  4. 53.]


In [19]:
x4= np.array([1,2,4,53])
new = np.float32(x4)
new_1=np.int_(new)
print("Data Type : ",new.dtype)
print("Data Type : ",new_1.dtype)
print(new)
print(new_1)

Data Type :  float32
Data Type :  int32
[ 1.  2.  4. 53.]
[ 1  2  4 53]
