Shape

In [1]:
import numpy as np

In [26]:
x= np.array([1,2,3,4,5,6,7,8,9,10,11,12,13],ndmin=4)
print(x)
print(x.ndim)
print(x.shape)

[[[[ 1  2  3  4  5  6  7  8  9 10 11 12 13]]]]
4
(1, 1, 1, 13)


3D-Array

In [21]:
x1= np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18])
new_1=x1.reshape(3,3,2)
print(new_1)
print(new_1.shape)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]]
(3, 3, 2)


2D-Array

In [22]:
x2= np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18])
new_2= x2.reshape(3,6)
print(new_2)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]


In [30]:
x3=np.array([[ 1  2  3  4  5  6],[ 7  8  9 10 11 12],[13 14 15 16 17 18]])
print(x3.shape)


SyntaxError: invalid syntax. Perhaps you forgot a comma? (2807363195.py, line 1)